vitessio/vitess-bot

- .dockerignore
This PR removes the `.env` file from `.dockerignore` so we can use the `.env` configuration on the production server.
> Removed .env from dockerignore

- .dockerignore
Remove the *.pem files in dockerignore so they can be used in Docker
> Removed *.pem from dockerignore

- index.js
This Pull Request changes the bot to enable both forwardport and backport of a given PR. The code was changed so we can allow for both port type for the same PR. i.e. a PR can now be backported and forwardported. This can be useful if we fix something on a recent release branch and we need to forwardport it to main but also older release branches.
A demo of this new behavior can be observed [here](https://github.com/frouioui/demo-gh-action-concurrency/pull/82). Ignore the very last comment from the bot. It was published by the bot that runs in production. :)
Closes #7.
> Allow forwardport and backport

- index.js
This Pull Request fixes the condition to restrict the scope of the review checklist comment. It was previously commenting on any `vitessio` repository, it now comments only on `vitessio/vitess`.
> Fix the review checklist repo/owner pre-condition

- index.js
This Pull Request adds a new endpoint to the bot that auto-documents the query serving the error codes of Vitess.
Each time a pull request is opened or synchronized, the bot will go through the list of modified files for this Pull Request and search if `go/vt/vterrors/code.go` (the file that lists all the error codes) has been modified.
If it is, we will generate the README version of the error codes (using the new code in https://github.com/vitessio/vitess/pull/10738).
We then determine if the new README is different than the one on the main branch of the docs repository. If the content of `content/en/docs/15.0/reference/errors/query-serving.md` that is in between the two new tags `` and ``. Those tags were added to the docs in this Pull Request: …
> Automatic documentation for vitess error code

- Dockerfile
- package.json
This PR upgrades the node version to a more recent version. And changes the Docker images from `slim` to `buster`. The slim image did not contain the `git` command (along with a lot of other utilities) which was failing the auto-documentation feature of the vitess-bot.
Additionally, this PR installs the Go library in the docker image.
> Use node 19 and buster Docker image and install Go

- index.js
This Pull Request adds some `console.log` to analyze the reasons why sometimes the bot is unable to backport a PR even though there are no conflicts.
> Log whenever there is a failure during a backport

- index.js
This PR changes the path used to run the error generation script in Vitess. The path of the script changed in https://github.com/vitessio/vitess/pull/10738.
> Fix the path taken to go run the error generation script in vitess

- index.js
This PR changes how we generate the query serving error documentation. The documentation will now be placed in the proper release documentation folder. By default the folder will be on `16.0`, and if the base of the Pull Request is a release branch, we parse the output version folder from the branch name.
> Generate error documentation based on the incoming release branch

- index.js
As discussed in our previous open hour, we want to invite reviewers to check if PR authors have added code documentation for tests.
> Update the review template to enforce test documentation

- index.js
This PR is a follow up of the work done in https://github.com/vitessio/vitess/pull/12062 and applies what was suggested in https://github.com/vitessio/vitess/pull/12062#pullrequestreview-1242731959.
When a PR is created, the bot will automatically add the `NeedsWebsiteDocsUpdate` and `NeedsDescriptionUpdate` labels to the PR. An example is available here: https://github.com/vitessio/vitess/pull/12078.
> Add `Needs...` labels to PR on creation

- Dockerfile
This bumps the golang version used by the docker image of the vitess-bot from `1.19` to `1.20`.
> bump the golang version used in the docker image

- go/pull_request_comments.go
This PR enhances the already existing handlers for the `pull_request` event by adding the three default labels to the PR upon creation.
> Addition of labels to opened pull requests

- go/documentation_generation.go
There was an issue with how we were detecting error code changes in Pull Request. In most cases we were not detecting any changes to the `code.go` file and thus we were not creating the documentation PR on the website repository.
> Fix how we detect error code changes

- go/documentation_generation.go
- go/git/branch.go
- go/git/repo.go
- go/main.go
- go/porting.go
- go/pull_request.go
- go/shell/shell.go
to merge after #58
This gives handlers dedicated working directories
this is in advance of the introduction of a second handler for releases,
and this will allow the two handlers to manage their own repo locks,
checkouts, parallelization, etc.
seems to work ok: https://github.com/ajm188/website/pull/7 via https://github.com/ajm188/vitess/pull/8
> handler workdirs

- go/cobradocs_sync.go
- go/documentation_generation.go
- go/git/pull_request.go
- go/pull_request.go
right now have this working through to syncing the docs for a _merged_ PR
i want to also provide support  for previewing doc changes based on either {main+the PR} or {releasebranch+the PR} if that nomenclature makes sense
finally i want to support also generate the sync pr when we _create_ tags for a release
> cobradocs sync

- README.md
- go/cobradocs_sync.go
- go/config.go
- go/git/pull_request.go
- go/git/repo.go
- go/main.go
- go/pull_request.go
- go/release_handler.go
- go/semver/semver.go
- go/semver/semver_test.go
this adds a new handler, ReleaseHandler, which updates COBRADOC_VERSION_PAIRS and regenerates the cobradocs whenever we _publish_ (not set in draft) a new release.
It makes a few assumptions:
- versions in a major line only ever go up. that is to say, if we were to accidentally cut `1.2.3` and _then_ publish `1.2.2`, then `1.2.2` would be the "latest" 1.0 version in the generated docs. doing the work to guard against this felt unnecessary
- ~~if we are publishing multiple releases (i.e. `1.2.1` and `2.1.2`) we will merge the doc PR for the first release before publishing the second release. this ... kinda sucks but for us to update the PAIRS variable we'd essentially be conflicting all over the place.~~
- ~~it would be _rad_ if we had a mechanism to signal "hey, releases are coming" and …
> add release handler to update released cobradocs when a release is published

- go/main.go
- go/pull_request.go
Based on #60 to merge afterwards.
This adds functionality to preview cobradoc changes
This occurs on PRs opened against either the `main` branch or `release-`
branches. The strategy here is to always have the PR consist of two
commits; the first commit is the docs generated against the base ref of
the PR, and the second commit is the docs generated against the head ref
of the PR. It's possible, but unlikely, that the first commit will be
empty, but the second commit will always contain a diff. These preview PRs
should never be merged, anyway.
See https://github.com/ajm188/website/pull/14 and https://github.com/ajm188/website/pull/15 for some demonstrations
> cobradocs preview

- go/cobradocs_sync.go
- go/git/repo.go
- go/pull_request.go
Compare https://github.com/vitessio/vitess-bot/blob/main/go/documentation_generation.go#L66 vs https://github.com/vitessio/vitess-bot/blob/main/go/cobradocs_sync.go#L131
The issue here is effectively never `pull` after the first clone, which is (I think) why sync PRs havent' been properly generated.
> Checkout FETCH_HEAD, not HEAD when setting up repos for cobradocs sync

- go/pull_request.go
- go/shell/shell.go
- go/shell/shell_darwin.go
- go/shell/shell_unix.go
Managed to finally get my hands on a relevant log entry and saw:
```
{"level":"error","github_event_type":"pull_request","github_delivery_id":"<omitted>","error":"Failed to `find` latest docs version to generate cobradocs preview for https://github.com/vitessio/vitess/pull/14789: exit status 1\nstderr: find: unknown predicate `-sE'\n\nstdout: ","time":"2024-01-24T13:13:22Z","message":"Unexpected error handling webhook"}
```
So, we need to remove `-sE` on unix, but not on darwin.
`-E` _before_ the path is replaced by `-regextype posix-extended` _after_ the path.
There is no replacement for `-s` on non-darwin unix, so we now need to pipe to `sort` to sort in dictionary order.
---
Tested running this on both my laptop:
```
➜  vtwebsite git:(cross-platform-find) ✗ bash -c "find -E …
```
> Run `find` in a cross-platform manner

- go/pull_request.go
This is how `cloneVitessAndGenerateErrors` clones; the advantage here is when the PR is based on a branch of a remote _other_ than the repo the PR is against (e.g. `planetscale/vitess` vs `vitessio/vitess`), we can fetch the PR's `HEAD` without needing to add a remote for that repository.
Didn't come up in my local testing as I was opening PRs against the same repo (`ajm188/vitess`).
See https://github.com/vitessio/vitess-bot/blob/main/go/documentation_generation.go#L62 for ex
> Fetch by PR number rather than ref

- go.mod
- go.sum
- go/git/diff_tree.go
- go/git/diff_tree_test.go
- go/git/repo.go
- go/pull_request.go
- go/shell/shell_darwin.go
- go/shell/shell_unix.go
Primary change here is replacing `website.Push` with a combination of `client.Git.CreateTree` + `client.Git.CreateCommit` + `client.Git.UpdateRef`, as the latter set of operations uses the authenticated context for our bot as opposed to simply shelling out, which does not have the necessary access.
> Use GitHub API for push operations

- go/cobradocs_sync.go
- go/pull_request.go
- go/shell/shell.go
Tested with https://github.com/ajm188/website/pull/17
Some relevant log lines from the testing:
```
{"level":"info","github_event_type":"pull_request","github_delivery_id":"e6283e60-bf75-11ee-958a-25db88c0abee","github_installation_id":42461852,"github_repository_owner":"ajm188","github_repository_name":"vitess","github_pr_num":14,"time":"2024-01-30T09:54:15-05:00","message":"No cobradocs changed for PR https://github.com/ajm188/vitess.git/vitess#14 at base release-18.0. Skipping first commit ..."}
```
```
{"level":"info","github_event_type":"pull_request","github_delivery_id":"38f51910-bf80-11ee-942a-1075829bfa8d","github_installation_id":42461852,"github_repository_owner":"ajm188","github_repository_name":"vitess","github_pr_num":14,"time":"2024-01-30T09:59:54-05:00","message":"closing …
```
> Close doc preview on release merge

- go/documentation_generation.go
- go/pull_request.go
- tools/get_release_from_docs.sh
In this PR I am doing a little refactor of the `PullRequestHandler`'s `Handle` method as it was becoming hard to read. I continued by changing how we detect the version of the docs where we need to update the error code documentation. It used to copy a shell script from the vitess-bot repository into the temporary cloned directory, which lead to keeping stale files on the repository and having to execute shell commands. Moreover, the script we used was not supporting release branches, only main. Meaning that only modification to the error codes on `main` were taken into account, backport to release branches were in some way ignored.
> Enhance and optimize the error code generation 

- go/pull_request.go
We are generating a huge number of branches for the cobradocs sync which we don't merge. This PR disables this functionality.
> Don't sync cobradocs on website
